"use client";
import { useMemo,useState } from "react";
import Link from "next/link";
import ProductCard from "@/components/products/ProductCard";
import QuickViewModal from "@/components/products/QuickViewModal";
import type { Category,Product } from "@/lib/types";

export default function ShopClient({products,categories,category,q}:{products:Product[];categories:Category[];category:string;q:string}){
 const[quick,setQuick]=useState<Product|null>(null);const[sub,setSub]=useState("");const[customOnly,setCustomOnly]=useState(false);const[sort,setSort]=useState("featured");
 const current=category?categories.find(c=>c.slug===category):undefined;const heading=q?`Search: ${q}`:(current?.name||"Shop XLIME");
 const list=useMemo(()=>{let r=[...products];if(sub)r=r.filter(p=>p.subcategory===sub);if(customOnly)r=r.filter(p=>p.isCustomizable);if(sort==="name")r.sort((a,b)=>a.name.localeCompare(b.name));else if(sort==="featured")r.sort((a,b)=>Number(b.featured)-Number(a.featured));return r},[products,sub,customOnly,sort]);
 const subs=current?.subcategories||Array.from(new Set(products.map(p=>p.subcategory))).slice(0,14);
 return <><div className="page-hero"><div className="wrap"><div className="breadcrumbs">Home › Shop{current?` › ${current.name}`:""}</div><h1 className="page-title">{heading}</h1><p className="muted" style={{maxWidth:760}}>{q?`Products matching “${q}”.`:(current?.description||"Sports, Gym & Active, Leather and Fashion — organised so shoppers can find the right XLIME product quickly.")}</p><div className="shop-category-pills"><Link href="/shop">All products</Link>{categories.map(c=><Link key={c.id} href={`/shop/${c.slug}`}>{c.name}</Link>)}</div></div></div><section className="section"><div className="wrap shop-layout"><aside className="filters"><div className="eyebrow">Filters</div><div className="filter-block"><b>Main category</b><label><input type="radio" name="main" checked={!category} readOnly/> <Link href="/shop">All products</Link></label>{categories.map(c=><label key={c.id}><input type="radio" name="main" checked={category===c.slug} readOnly/> <Link href={`/shop/${c.slug}`}>{c.name}</Link></label>)}</div><div className="filter-block"><b>Subcategory</b><label><input type="radio" name="sub" checked={!sub} onChange={()=>setSub("")}/> All</label>{subs.map(s=><label key={s}><input type="radio" name="sub" checked={sub===s} onChange={()=>setSub(s)}/> {s}</label>)}</div><div className="filter-block"><b>Order type</b><label><input type="checkbox" checked={customOnly} onChange={e=>setCustomOnly(e.target.checked)}/> Customisable products</label></div></aside><div><div className="section-head"><div><span className="eyebrow">{list.length} products</span><h2 className="h2" style={{fontSize:42}}>Browse collection</h2></div><label className="shop-sort">Sort <select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="name">Name A–Z</option></select></label></div><div className="grid-products">{list.map(p=><ProductCard key={p.id} product={p} onQuickView={setQuick}/>)}</div>{!list.length&&<div className="form-card" style={{marginTop:14}}>No products match the selected filters. Clear a filter or explore another XLIME category.</div>}</div></div></section>{quick&&<QuickViewModal product={quick} onClose={()=>setQuick(null)}/>}</>;
}
