import type { Metadata } from "next";
import { notFound } from "next/navigation";
import SiteFrame from "@/components/layout/SiteFrame";
import ProductDetailClient from "@/components/products/ProductDetailClient";
import { serverApi,siteUrl } from "@/lib/server-api";
import type { Product } from "@/lib/types";
import { jsonLd } from "@/lib/jsonld";

async function getProduct(slug:string){try{return (await serverApi<{product:Product}>(`/products/${slug}`,{next:{revalidate:300}} as any)).product}catch{return null}}
async function getRelated(p:Product){try{const r=await serverApi<{products:Product[]}>(`/products?category=${encodeURIComponent(p.category.slug)}`,{next:{revalidate:300}} as any);return r.products.filter(x=>x.id!==p.id).slice(0,6)}catch{return [] as Product[]}}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const p=await getProduct(slug);if(!p)return {title:"Product Not Found",robots:{index:false,follow:false}};const title=p.seoTitle||p.name;const description=p.seoDescription||p.shortDescription;return {title:{absolute:title},description,alternates:{canonical:`/product/${p.slug}`},openGraph:{type:"website",url:`${siteUrl}/product/${p.slug}`,title,description,images:[{url:p.imageUrl,alt:p.altText||p.name}]},twitter:{card:"summary_large_image",title,description,images:[p.imageUrl]}}}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const p=await getProduct(slug);if(!p)notFound();const related=await getRelated(p);const productJsonLd:any={"@context":"https://schema.org","@type":"Product",name:p.name,image:[p.imageUrl,...p.images.map(i=>i.url)],description:p.description,sku:p.sku||p.slug,brand:{"@type":"Brand",name:"XLIME GEAR"},category:`${p.category.name} > ${p.subcategory}`,url:`${siteUrl}/product/${p.slug}`};if(p.showPrice&&p.pricePence!=null)productJsonLd.offers={"@type":"Offer",priceCurrency:"GBP",price:(p.pricePence/100).toFixed(2),availability:(p.stockQuantity??0)>0?"https://schema.org/InStock":"https://schema.org/OutOfStock",url:`${siteUrl}/product/${p.slug}`};const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:siteUrl},{"@type":"ListItem",position:2,name:p.category.name,item:`${siteUrl}/shop/${p.category.slug}`},{"@type":"ListItem",position:3,name:p.name,item:`${siteUrl}/product/${p.slug}`}]};return <SiteFrame><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(productJsonLd)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(breadcrumb)}}/><div className="page-hero"><div className="wrap"><div className="breadcrumbs">Home › {p.category.name} › {p.name}</div></div></div><ProductDetailClient product={p} related={related}/></SiteFrame>}
