"use client";
import { Suspense,useEffect,useState } from "react";
import { useParams,useSearchParams } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import SiteFrame from "@/components/layout/SiteFrame";
import { api,assetUrl } from "@/lib/api";
import type { Order } from "@/lib/types";

function ConfirmationContent(){const{orderNumber}=useParams<{orderNumber:string}>();const params=useSearchParams();const[order,setOrder]=useState<Order|null>(null);const[error,setError]=useState("");useEffect(()=>{api<{order:Order}>(`/orders/${orderNumber}?email=${encodeURIComponent(params.get("email")||"")}`).then(r=>setOrder(r.order)).catch(e=>setError(e.message))},[orderNumber,params]);const city=order?.deliveryAddress?.city||"—";return <SiteFrame><div className="page-hero"><div className="wrap"><span className="eyebrow">Request confirmed</span><h1 className="page-title">Request submitted successfully.</h1><p className="muted">XLIME has received the request and can now review sizes, availability, custom details and the next fulfilment step.</p></div></div><section className="section"><div className="wrap checkout-grid"><div className="form-card order-success"><div className="success-mark">✓</div><span className="eyebrow">Thank you{order?.customerName?`, ${order.customerName.split(" ")[0]}`:""}</span><h2 className="display" style={{fontSize:46,margin:"8px 0"}}>Your XLIME order request is confirmed.</h2><p className="muted">Your request is stored in the production database and is available to the XLIME Operations Hub for review and follow-up.</p><div className="confirmation-grid"><div><span>Order number</span><b>{orderNumber}</b></div><div><span>Email</span><b>{order?.email||params.get("email")||"—"}</b></div><div><span>Delivery to</span><b>{city}</b></div><div><span>Order status</span><b>{order?.status?.replaceAll("_"," ")||"PENDING REVIEW"}</b></div></div>{error&&<p className="checkout-error">{error}</p>}<div className="hero-actions"><Link className="btn primary" href="/shop">Continue shopping</Link><Link className="btn" href="/account">View account</Link></div></div><aside className="summary"><h2 className="display" style={{fontSize:34,marginTop:0}}>Order items</h2>{order?.items?.length?order.items.map(i=><div className="drawer-item" key={i.id}><Image src={assetUrl(i.imageUrl)} width={80} height={66} alt={i.productName}/><div><b>{i.productName}</b><div className="muted">Qty {i.quantity}</div></div><span className="enquire-mini">Requested</span></div>):<p className="muted">Loading submitted items…</p>}<div className="order-note"><b>Order details by enquiry</b><span>XLIME will confirm the final order details directly.</span></div></aside></div></section></SiteFrame>}
export default function Confirmation(){return <Suspense fallback={<div className="section wrap">Loading order confirmation…</div>}><ConfirmationContent/></Suspense>}
