"use client";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { adminApi } from "@/lib/admin";
import { AdminPageHeader,Panel } from "@/components/admin/AdminUI";
import { Save,Shirt } from "lucide-react";
export default function NewCustomKitPage(){const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{const fd=new FormData(e.currentTarget);const r=await adminApi.post<any>("/custom-kits",{teamName:fd.get("teamName")||null,sport:fd.get("sport"),primaryColor:fd.get("primaryColor"),secondaryColor:fd.get("secondaryColor"),playerName:fd.get("playerName")||null,playerNumber:fd.get("playerNumber")||null,crestUrl:fd.get("crestUrl")||null,notes:fd.get("notes")||null,stage:"NEW"});router.push(`/admin/custom-kits/${r.request.id}`)}catch(x:any){setError(x.message||"Unable to create custom kit request")}finally{setBusy(false)}}return <><AdminPageHeader eyebrow="CUSTOM KIT / DESIGN WORKFLOW" title="Create Custom Kit Request" description="Capture an offline or internal design brief and place it directly into the production workflow." actions={<Link className="adm-btn" href="/admin/custom-kits">Cancel</Link>}/><form onSubmit={submit}><div className="adm-detail-grid"><div className="adm-grid"><Panel title="Kit Brief"><div className="adm-detail-block"><div className="adm-form-grid"><Field label="Team name" name="teamName"/><Field label="Sport *" name="sport" defaultValue="Football" required/><Field label="Player name" name="playerName"/><Field label="Player number" name="playerNumber"/><div className="adm-field"><label>Primary colour</label><input className="adm-input" type="color" name="primaryColor" defaultValue="#C8FF00"/></div><div className="adm-field"><label>Secondary colour</label><input className="adm-input" type="color" name="secondaryColor" defaultValue="#080A08"/></div><div className="adm-field wide"><label>Crest URL</label><input className="adm-input" type="url" name="crestUrl" placeholder="https://…"/></div><div className="adm-field wide"><label>Design notes</label><textarea className="adm-textarea" name="notes" placeholder="Colours, patterns, sponsor marks, sizing, quantity, delivery or artwork notes…"/></div></div></div></Panel></div><aside className="adm-grid" style={{alignContent:"start"}}><Panel title="Design Queue"><div className="adm-detail-block"><Shirt size={22} style={{color:"var(--adm-lime)"}}/><p style={{color:"var(--adm-sub)",fontSize:12,lineHeight:1.7}}>The request starts as <b>New</b> and can then move through design review, assets, revisions, quote, approval, production and quality control.</p>{error&&<p style={{color:"var(--adm-danger)",fontSize:11}}>{error}</p>}<button className="adm-btn primary" disabled={busy} style={{width:"100%",justifyContent:"center"}}><Save size={14}/>{busy?"Creating…":"Create Kit Request"}</button></div></Panel></aside></div></form></>}
function Field(p:any){return <div className="adm-field"><label>{p.label}</label><input className="adm-input" {...p} label={undefined}/></div>}
