import type { Metadata } from "next";
import { notFound } from "next/navigation";
import SiteFrame from "@/components/layout/SiteFrame";
import ProductCard from "@/components/products/ProductCard";
import { serverApi,siteUrl } from "@/lib/server-api";
import { slugifyPath } from "@/lib/seo";
import Link from "next/link";
import type { Category,Product } from "@/lib/types";
import { jsonLd } from "@/lib/jsonld";
async function getData(slug:string){try{const[c,p]=await Promise.all([serverApi<{categories:Category[]}>("/products/categories"),serverApi<{products:Product[]}>(`/products?category=${encodeURIComponent(slug)}`)]);return{category:c.categories.find(x=>x.slug===slug)||null,products:p.products}}catch{return{category:null,products:[]}}}
export async function generateMetadata({params}:{params:Promise<{category:string}>}):Promise<Metadata>{const{category:slug}=await params;const d=await getData(slug);if(!d.category)return{title:"Category Not Found",robots:{index:false,follow:false}};const category=d.category;const title=category.seoTitle||`${category.name} | XLIME GEAR`;const description=category.seoDescription||category.description||`Explore ${category.name} from XLIME GEAR.`;return{title:{absolute:title},description,alternates:{canonical:`/shop/${slug}`},openGraph:{url:`${siteUrl}/shop/${slug}`,title,description,images:category.imageUrl?[{url:category.imageUrl,alt:`XLIME GEAR ${category.name}`}]:[]}}}
export default async function CategoryPage({params}:{params:Promise<{category:string}>}){const{category:slug}=await params;const d=await getData(slug);if(!d.category)notFound();const category=d.category;const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:siteUrl},{"@type":"ListItem",position:2,name:"Shop",item:`${siteUrl}/shop`},{"@type":"ListItem",position:3,name:category.name,item:`${siteUrl}/shop/${slug}`}]};return <SiteFrame><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(breadcrumb)}}/><div className="page-hero"><div className="wrap"><div className="breadcrumbs">Home â€º Shop â€º {category.name}</div><h1 className="page-title">{category.name}</h1><p className="muted" style={{maxWidth:680}}>{category.description}</p>{(category.subcategories||[]).length>0&&<div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:18}}>{(category.subcategories||[]).map(sub=><Link className="pill" key={sub} href={`/shop/${category.slug}/${slugifyPath(sub)}`}>{sub}</Link>)}</div>}</div></div><section className="section"><div className="wrap"><div className="grid-products">{d.products.map(p=><ProductCard key={p.id} product={p}/>)}</div>{!d.products.length&&<p>No active products are currently available in this category.</p>}</div></section></SiteFrame>}
