"use client";
import { useEffect,useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { adminApi,fmtDateTime,pretty,fmtMoney } from "@/lib/admin";
import { api,assetUrl } from "@/lib/api";
import { AdminPageHeader,Panel,StatusBadge,LoadingState } from "@/components/admin/AdminUI";
const statuses=["REQUESTED","CONFIRMED","IN_PRODUCTION","READY_TO_SHIP","SHIPPED","COMPLETED","CANCELLED"];
export default function OrderDetails(){const{id}=useParams<{id:string}>();const[order,setOrder]=useState<any>(null);const load=()=>adminApi.get<any>(`/orders/${id}`).then(r=>setOrder(r.order));useEffect(()=>{load()},[id]);const update=async(status:string)=>{await api(`/admin/orders/${id}`,{method:"PATCH",body:JSON.stringify({status})});load()};if(!order)return <LoadingState/>;const addr=order.deliveryAddress||{};return <><AdminPageHeader eyebrow="ORDERS / DETAIL" title={`Order ${order.orderNumber}`} description={`Submitted ${fmtDateTime(order.createdAt)}`} actions={<><Link className="adm-btn" href="/admin/orders">Back to Orders</Link><select className="adm-select" value={order.status} onChange={e=>update(e.target.value)}>{statuses.map(s=><option value={s} key={s}>{pretty(s)}</option>)}</select></>}/><div className="adm-detail-grid"><div className="adm-grid"><Panel title="Items"><div className="adm-table-wrap"><table className="adm-table"><thead><tr><th>Item</th><th>Quantity</th><th>Customisation</th></tr></thead><tbody>{order.items.map((i:any)=><tr key={i.id}><td><div className="adm-product-cell"><img src={assetUrl(i.imageUrl)} alt={i.productName}/><div><b>{i.productName}</b><small>{i.productSlug}</small></div></div></td><td>{i.quantity}</td><td>{i.customisation?JSON.stringify(i.customisation):"—"}</td></tr>)}</tbody></table></div></Panel><Panel title="Order Timeline"><div className="adm-timeline">{statuses.filter(s=>s!=="CANCELLED").map((s,idx)=><div className="adm-timeline-item" key={s}><b>{pretty(s)}</b><p>{order.status===s?"Current stage":statuses.indexOf(order.status)>idx?"Completed":"Pending"}</p></div>)}</div></Panel></div><aside className="adm-grid" style={{alignContent:"start"}}><Panel title="Customer"><div className="adm-detail-block"><dl className="adm-detail-list"><div><dt>Name</dt><dd>{order.customerName}</dd></div><div><dt>Email</dt><dd>{order.email}</dd></div><div><dt>Phone</dt><dd>{order.phone}</dd></div><div><dt>Status</dt><dd><StatusBadge value={order.status}/></dd></div></dl></div></Panel><Panel title="Delivery"><div className="adm-detail-block" style={{fontSize:11,lineHeight:1.7}}>{addr.fullName&&<b>{addr.fullName}<br/></b>}{addr.line1}<br/>{addr.line2&&<>{addr.line2}<br/></>}{addr.city} {addr.postcode}<br/>{addr.country}</div></Panel><Panel title="Internal"><div className="adm-detail-block"><p style={{fontSize:10,color:"var(--adm-muted)"}}>{order.notes||"No internal notes."}</p>{order.internalValuePence!=null&&<p><b>Internal value:</b> {fmtMoney(order.internalValuePence)}</p>}</div></Panel></aside></div></>}
