"use client";
import { useEffect,useState } from "react";
import { api } from "@/lib/api";
import { AdminPageHeader,Panel,MetricCard,Modal,EmptyState } from "@/components/admin/AdminUI";
import { Plus,Edit3,Trash2 } from "lucide-react";

const blank={name:"",slug:"",description:"",imageUrl:"",sortOrder:0,isActive:true,subcategories:[] as string[],seoTitle:"",seoDescription:""};
const slugify=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export default function CategoriesPage(){
 const[categories,setCategories]=useState<any[]>([]);const[editing,setEditing]=useState<any>(null);const[sub,setSub]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 const load=()=>{setLoading(true);setError("");return api<any>("/admin/categories").then(r=>setCategories(r.categories||[])).catch(e=>setError(e.message||"Unable to load categories.")).finally(()=>setLoading(false))};useEffect(()=>{void load()},[]);
 const save=async()=>{const body={...editing,slug:editing.slug||slugify(editing.name),sortOrder:Number(editing.sortOrder||0)};if(editing.id)await api(`/admin/categories/${editing.id}`,{method:"PATCH",body:JSON.stringify(body)});else await api("/admin/categories",{method:"POST",body:JSON.stringify(body)});setEditing(null);load()};
 const del=async(c:any)=>{if(!confirm(`Delete ${c.name}? Categories assigned to active products are protected.`))return;try{await api(`/admin/categories/${c.id}`,{method:"DELETE"});load()}catch(e:any){alert(e.message)}};
 const addSub=()=>{const v=sub.trim();if(!v)return;setEditing((x:any)=>({...x,subcategories:[...(Array.isArray(x.subcategories)?x.subcategories:[]),v]}));setSub("")};
 return <>
  <AdminPageHeader title="Categories" description="Structure the XLIME catalog with clean parent categories and protected subcategories." actions={<button className="adm-btn primary" onClick={()=>setEditing({...blank})}><Plus size={14}/>Add Category</button>}/>
  {error&&<Panel><div className="adm-empty"><strong>Unable to load categories</strong><p>{error}</p><button className="adm-btn" onClick={()=>void load()}>Retry</button></div></Panel>}
  <div className="adm-grid metrics" style={{gridTemplateColumns:"repeat(3,minmax(0,1fr))"}}><MetricCard label="Categories" value={categories.length}/><MetricCard label="Subcategories" value={categories.reduce((n,c)=>n+(Array.isArray(c.subcategories)?c.subcategories.length:0),0)}/><MetricCard label="Active" value={categories.filter(c=>c.isActive!==false).length}/></div>
  <div className="adm-grid">{loading?<Panel><div className="adm-loading">Loading categories...</div></Panel>:categories.map(c=><Panel key={c.id} title={c.name} subtitle={`${Array.isArray(c.subcategories)?c.subcategories.length:0} subcategories • /shop/${c.slug}`} action={<div style={{display:"flex",gap:5}}><button className="adm-icon-btn" onClick={()=>setEditing({...c,subcategories:Array.isArray(c.subcategories)?c.subcategories:[]})}><Edit3 size={14}/></button><button className="adm-icon-btn" onClick={()=>del(c)}><Trash2 size={14}/></button></div>}><div className="adm-detail-block"><p style={{fontSize:11,color:"var(--adm-muted)",marginTop:0}}>{c.description||"No description"}</p><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{(Array.isArray(c.subcategories)?c.subcategories:[]).map((s:string)=><span className="adm-status neutral" key={s}>{s}</span>)}</div></div></Panel>)}{!loading&&!categories.length&&<Panel><EmptyState title="No categories yet"/></Panel>}</div>
  <Modal open={!!editing} title={editing?.id?"Edit Category":"Add Category"} onClose={()=>setEditing(null)} footer={<><button className="adm-btn" onClick={()=>setEditing(null)}>Cancel</button><button className="adm-btn primary" onClick={save}>Save Category</button></>}>
   {editing&&<div className="adm-form-grid"><div className="adm-field"><label>Name *</label><input className="adm-input" value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value,slug:editing.id?editing.slug:slugify(e.target.value)})}/></div><div className="adm-field"><label>Slug</label><input className="adm-input" value={editing.slug} onChange={e=>setEditing({...editing,slug:slugify(e.target.value)})}/></div><div className="adm-field wide"><label>Description</label><textarea className="adm-textarea" value={editing.description||""} onChange={e=>setEditing({...editing,description:e.target.value})}/></div><div className="adm-field"><label>Image URL</label><input className="adm-input" value={editing.imageUrl||""} onChange={e=>setEditing({...editing,imageUrl:e.target.value})}/></div><div className="adm-field"><label>Sort order</label><input type="number" className="adm-input" value={editing.sortOrder||0} onChange={e=>setEditing({...editing,sortOrder:Number(e.target.value)})}/></div><div className="adm-field wide"><label>Subcategories</label><div className="adm-toolbar"><input className="adm-input" value={sub} onChange={e=>setSub(e.target.value)} placeholder="e.g. Sports Bras"/><button className="adm-btn" onClick={addSub}>Add</button></div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{editing.subcategories.map((s:string)=><button className="adm-status neutral" key={s} onClick={()=>setEditing({...editing,subcategories:editing.subcategories.filter((x:string)=>x!==s)})}>{s} ×</button>)}</div></div><div className="adm-field wide"><label>SEO title</label><input className="adm-input" value={editing.seoTitle||""} onChange={e=>setEditing({...editing,seoTitle:e.target.value})}/></div><div className="adm-field wide"><label>Meta description</label><textarea className="adm-textarea" value={editing.seoDescription||""} onChange={e=>setEditing({...editing,seoDescription:e.target.value})}/></div></div>}
  </Modal>
 </>
}
