import { Router } from "express";
import { adminController } from "../controllers/admin.controller.js";
import { requireAdmin } from "../middleware/auth.middleware.js";
import { requirePermission } from "../middleware/permission.middleware.js";
import { validate } from "../middleware/validate.middleware.js";
import { createProductSchema, updateProductSchema, orderStatusSchema, requestStatusSchema, createCategorySchema, updateCategorySchema, productImageSchema } from "../validators/admin.validator.js";

export const adminRoutes = Router();
adminRoutes.use(requireAdmin);
adminRoutes.get("/dashboard", requirePermission("dashboard.view"), adminController.dashboard);
adminRoutes.get("/categories", requirePermission("categories.manage"), adminController.categories);
adminRoutes.post("/categories", requirePermission("categories.manage"), validate(createCategorySchema), adminController.createCategory);
adminRoutes.patch("/categories/:id", requirePermission("categories.manage"), validate(updateCategorySchema), adminController.updateCategory);
adminRoutes.delete("/categories/:id", requirePermission("categories.manage"), adminController.deleteCategory);
adminRoutes.get("/products", requirePermission("products.manage"), adminController.products);
adminRoutes.post("/products", requirePermission("products.manage"), validate(createProductSchema), adminController.createProduct);
adminRoutes.patch("/products/:id", requirePermission("products.manage"), validate(updateProductSchema), adminController.updateProduct);
adminRoutes.delete("/products/:id", requirePermission("products.manage"), adminController.deleteProduct);
adminRoutes.post("/products/:id/duplicate", requirePermission("products.manage"), adminController.duplicateProduct);
adminRoutes.post("/products/:id/images", requirePermission("products.manage"), validate(productImageSchema), adminController.addProductImage);
adminRoutes.delete("/products/:id/images/:imageId", requirePermission("products.manage"), adminController.deleteProductImage);
adminRoutes.patch("/products/:id/images/:imageId/cover", requirePermission("products.manage"), adminController.setProductCover);
adminRoutes.get("/orders", requirePermission("orders.manage"), adminController.orders);
adminRoutes.patch("/orders/:id", requirePermission("orders.manage"), validate(orderStatusSchema), adminController.updateOrder);
adminRoutes.get("/team-orders", requirePermission("teamOrders.manage"), adminController.teamOrders);
adminRoutes.patch("/team-orders/:id", requirePermission("teamOrders.manage"), validate(requestStatusSchema), adminController.updateTeamOrder);
adminRoutes.get("/custom-kits", requirePermission("customKits.manage"), adminController.customKits);
adminRoutes.patch("/custom-kits/:id", requirePermission("customKits.manage"), validate(requestStatusSchema), adminController.updateCustomKit);
adminRoutes.get("/users", requirePermission("customers.manage"), adminController.users);
