import { z } from "zod";
const route = <T extends z.ZodTypeAny>(body:T, params:z.ZodTypeAny=z.object({}), query:z.ZodTypeAny=z.object({})) => z.object({ body, params, query });

const collectionBody = z.object({ name:z.string().min(2).max(120), slug:z.string().regex(/^[a-z0-9-]+$/), description:z.string().max(3000).optional().nullable(), imageUrl:z.string().max(3000).optional().nullable(), isActive:z.boolean().optional(), sortOrder:z.coerce.number().int().min(0).max(999).optional(), productIds:z.array(z.string().min(5).max(100)).max(200).optional() });
export const collectionSchema = route(collectionBody);
export const collectionUpdateSchema = route(collectionBody.partial(),z.object({id:z.string().min(5)}));
export const inventoryAdjustmentSchema = route(z.object({ newQuantity:z.coerce.number().int().min(0).max(1000000), reason:z.enum(["RESTOCK","CORRECTION","DAMAGED","RETURNED","MANUAL"]), note:z.string().max(1000).optional().nullable() }),z.object({id:z.string().min(5)}));
export const stageSchema = route(z.object({stage:z.string().min(2).max(64)}),z.object({id:z.string().min(5)}));
export const noteSchema = route(z.object({note:z.string().min(2).max(5000)}),z.object({id:z.string().min(5)}));
const quoteBody=z.object({ customerName:z.string().min(2).max(160), email:z.string().email(), phone:z.string().max(60).optional().nullable(), sourceType:z.string().max(40).default("MANUAL"), sourceId:z.string().optional().nullable(), status:z.string().max(40).default("DRAFT"), discountPence:z.coerce.number().int().min(0).default(0), deliveryPence:z.coerce.number().int().min(0).default(0), validUntil:z.string().datetime().optional().nullable(), internalNotes:z.string().max(10000).optional().nullable(), customerNotes:z.string().max(10000).optional().nullable(), items:z.array(z.object({description:z.string().min(1).max(500),quantity:z.coerce.number().int().min(1).max(100000),unitPence:z.coerce.number().int().min(0)})).min(1).max(100) });
export const quoteSchema=route(quoteBody);
export const quoteStatusSchema=route(z.object({status:z.enum(["DRAFT","SENT","AWAITING_RESPONSE","APPROVED","EXPIRED","CANCELLED"])}),z.object({id:z.string().min(5)}));
const teamAccountBody=z.object({ organisation:z.string().min(2).max(180), organisationType:z.string().max(60).default("Club"), sport:z.string().max(80).optional().nullable(), logoUrl:z.string().max(3000).optional().nullable(), primaryContact:z.string().min(2).max(160), email:z.string().email(), phone:z.string().max(60).optional().nullable(), secondaryContact:z.string().max(160).optional().nullable(), deliveryAddress:z.string().max(3000).optional().nullable(), notes:z.string().max(10000).optional().nullable() });
export const teamAccountSchema=route(teamAccountBody);
export const teamAccountUpdateSchema=route(teamAccountBody.partial(),z.object({id:z.string().min(5)}));
export const bannerSchema=route(z.object({ isActive:z.boolean(),isDismissible:z.boolean(),text:z.string().min(2).max(300),ctaText:z.string().max(60).optional().nullable(),ctaUrl:z.string().max(500).optional().nullable(),background:z.string().regex(/^#[0-9A-Fa-f]{6}$/),textColor:z.string().regex(/^#[0-9A-Fa-f]{6}$/),startAt:z.string().datetime().optional().nullable(),endAt:z.string().datetime().optional().nullable() }));
const campaignBody=z.object({ name:z.string().min(2).max(160),type:z.string().max(60),status:z.string().max(40),headline:z.string().min(2).max(240),description:z.string().max(5000).optional().nullable(),destination:z.string().max(500).optional().nullable(),startsAt:z.string().datetime().optional().nullable(),endsAt:z.string().datetime().optional().nullable() });
export const campaignSchema=route(campaignBody);
export const campaignUpdateSchema=route(campaignBody.partial(),z.object({id:z.string().min(5)}));
export const settingsSchema=route(z.record(z.string(),z.unknown()));
export const notificationReadSchema=route(z.object({isRead:z.boolean()}),z.object({id:z.string().min(5)}));
export const adminMembershipSchema=route(z.object({roleKey:z.string().min(2).max(80),isActive:z.boolean().optional()}),z.object({id:z.string().min(5)}));
export const createAdminUserSchema=route(z.object({name:z.string().trim().min(2).max(160),email:z.string().trim().toLowerCase().email().max(254),phone:z.string().trim().max(60).optional().nullable(),password:z.string().min(12).max(200).regex(/[A-Z]/,"Password needs an uppercase letter").regex(/[a-z]/,"Password needs a lowercase letter").regex(/[0-9]/,"Password needs a number"),roleKey:z.string().min(2).max(80)}));
export const mediaAssetSchema=route(z.object({fileName:z.string().min(1).max(255),url:z.string().min(1).max(3000),mimeType:z.string().max(120),alt:z.string().min(2).max(300),folder:z.string().max(100).optional(),width:z.coerce.number().int().positive().optional().nullable(),height:z.coerce.number().int().positive().optional().nullable(),sizeBytes:z.coerce.number().int().positive().optional().nullable()}));

export const adminTeamOrderCreateSchema=route(z.object({
  organisation:z.string().trim().min(2).max(180),contactName:z.string().trim().min(2).max(160),email:z.string().trim().toLowerCase().email().max(254),phone:z.string().trim().max(60).optional().nullable(),sport:z.string().trim().min(2).max(80).default("Football"),numberOfPlayers:z.coerce.number().int().min(1).max(100000).optional().nullable(),requirements:z.string().trim().min(5).max(5000),packageInterest:z.string().trim().max(120).optional().nullable(),deadline:z.string().datetime().optional().nullable(),stage:z.enum(["NEW_LEAD","CONTACTED","REQUIREMENTS","QUOTE_PREPARATION","QUOTE_SENT","APPROVED","PRODUCTION","QUALITY_CHECK","DISPATCHED","COMPLETED","CANCELLED"]).default("NEW_LEAD")
}));
export const adminCustomKitCreateSchema=route(z.object({
  teamName:z.string().trim().max(180).optional().nullable(),sport:z.string().trim().min(2).max(80).default("Football"),primaryColor:z.string().regex(/^#[0-9A-Fa-f]{6}$/).default("#C8FF00"),secondaryColor:z.string().regex(/^#[0-9A-Fa-f]{6}$/).default("#080A08"),playerName:z.string().trim().max(80).optional().nullable(),playerNumber:z.string().trim().max(20).optional().nullable(),crestUrl:z.string().url().max(3000).optional().nullable(),notes:z.string().trim().max(5000).optional().nullable(),stage:z.enum(["NEW","DESIGN_REVIEW","AWAITING_ASSETS","REVISION","REQUIREMENTS_CONFIRMED","QUOTED","APPROVED","PRODUCTION","QUALITY_CHECK","DISPATCHED","COMPLETED","CANCELLED"]).default("NEW")
}));

export const customKitAssetSchema=route(z.object({url:z.string().min(1).max(3000),type:z.enum(["REFERENCE","CREST","SPONSOR","ARTWORK","FINAL"]).default("REFERENCE"),label:z.string().trim().max(180).optional().nullable()}),z.object({id:z.string().min(5)}));
export const customKitRevisionSchema=route(z.object({previewUrl:z.string().min(1).max(3000),status:z.enum(["REVIEW","CHANGES_REQUESTED","APPROVED","REJECTED"]).default("REVIEW"),notes:z.string().trim().max(5000).optional().nullable()}),z.object({id:z.string().min(5)}));
