"use client";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { adminApi } from "@/lib/admin";
import { AdminPageHeader,Panel } from "@/components/admin/AdminUI";
import { Save,UsersRound } from "lucide-react";
export default function NewTeamOrderPage(){const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{const fd=new FormData(e.currentTarget);const deadline=String(fd.get("deadline")||"");const r=await adminApi.post<any>("/team-orders",{organisation:fd.get("organisation"),contactName:fd.get("contactName"),email:fd.get("email"),phone:fd.get("phone")||null,sport:fd.get("sport"),numberOfPlayers:Number(fd.get("numberOfPlayers")||0)||null,packageInterest:fd.get("packageInterest")||null,deadline:deadline?new Date(`${deadline}T12:00:00Z`).toISOString():null,requirements:fd.get("requirements"),stage:"NEW_LEAD"});router.push(`/admin/team-orders/${r.request.id}`)}catch(x:any){setError(x.message||"Unable to create team order") }finally{setBusy(false)}}return <><AdminPageHeader eyebrow="TEAM ORDERS / CRM" title="Create Team Order" description="Add a phone, WhatsApp or offline team enquiry directly into the XLIME pipeline." actions={<Link className="adm-btn" href="/admin/team-orders">Cancel</Link>}/><form onSubmit={submit}><div className="adm-detail-grid"><div className="adm-grid"><Panel title="Organisation & Contact"><div className="adm-detail-block"><div className="adm-form-grid"><Field label="Club / organisation *" name="organisation" required/><Field label="Contact name *" name="contactName" required/><Field label="Email *" name="email" type="email" required/><Field label="Phone" name="phone"/><Field label="Sport *" name="sport" defaultValue="Football" required/><Field label="Players" name="numberOfPlayers" type="number" min="1"/></div></div></Panel><Panel title="Requirements"><div className="adm-detail-block"><div className="adm-form-grid"><Field label="Package interest" name="packageInterest" placeholder="Essential / Performance / Elite"/><Field label="Deadline" name="deadline" type="date"/><div className="adm-field wide"><label>Requirements *</label><textarea className="adm-textarea" name="requirements" required placeholder="Kit type, quantities, colours, branding, sizes, deadline and any production notes…"/></div></div></div></Panel></div><aside className="adm-grid" style={{alignContent:"start"}}><Panel title="Pipeline"><div className="adm-detail-block"><UsersRound size={22} style={{color:"var(--adm-lime)"}}/><p style={{color:"var(--adm-sub)",fontSize:12,lineHeight:1.7}}>The lead starts in <b>New Lead</b>. Use the Team Orders board to move it through requirements, quote, production, QC and dispatch.</p>{error&&<p style={{color:"var(--adm-danger)",fontSize:11}}>{error}</p>}<button className="adm-btn primary" disabled={busy} style={{width:"100%",justifyContent:"center"}}><Save size={14}/>{busy?"Creating…":"Create Team Order"}</button></div></Panel></aside></div></form></>}
function Field(p:any){return <div className="adm-field"><label>{p.label}</label><input className="adm-input" {...p} label={undefined}/></div>}
