"use client";
import type { ReactNode } from "react";
import { Search, ChevronRight, Inbox, X, LoaderCircle } from "lucide-react";
import { pretty } from "@/lib/admin";

export function AdminPageHeader({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:ReactNode}){return <header className="adm-page-head"><div><span className="adm-eyebrow">{eyebrow||"XLIME OPERATIONS HUB"}</span><h1>{title}</h1>{description&&<p>{description}</p>}</div>{actions&&<div className="adm-page-actions">{actions}</div>}</header>}
export function MetricCard({label,value,detail,icon,accent="lime",onClick}:{label:string;value:ReactNode;detail?:string;icon?:ReactNode;accent?:string;onClick?:()=>void}){const C=onClick?"button":"div" as any;return <C className={`adm-metric adm-accent-${accent}`} onClick={onClick}><div className="adm-metric-top"><span>{label}</span>{icon&&<i>{icon}</i>}</div><strong>{value}</strong>{detail&&<small>{detail}</small>}</C>}
export function Panel({title,subtitle,action,children,className=""}:{title?:string;subtitle?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`adm-panel ${className}`}><div className="adm-panel-head">{title&&<div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>}{action&&<div>{action}</div>}</div>{children}</section>}
export function StatusBadge({value}:{value?:string|null}){const v=(value||"UNKNOWN").toUpperCase();const tone=v.includes("COMPLETED")||v.includes("APPROVED")||v.includes("ACTIVE")||v.includes("SHIPPED")?"success":v.includes("CANCEL")||v.includes("ARCHIVED")?"danger":v.includes("NEW")||v.includes("REQUEST")||v.includes("DRAFT")?"info":v.includes("LOW")||v.includes("AWAIT")||v.includes("QUOTE")||v.includes("REVIEW")?"warning":"neutral";return <span className={`adm-status ${tone}`}>{pretty(v)}</span>}
export function SearchBox({value,onChange,placeholder="Search..."}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="adm-search"><Search size={16}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
export function EmptyState({title="Nothing here yet",text="New records will appear here when available."}:{title?:string;text?:string}){return <div className="adm-empty"><Inbox size={36}/><strong>{title}</strong><p>{text}</p></div>}
export function LoadingState(){return <div className="adm-loading"><LoaderCircle className="spin" size={22}/>Loading live data…</div>}
export function Modal({open,title,onClose,children,footer}:{open:boolean;title:string;onClose:()=>void;children:ReactNode;footer?:ReactNode}){if(!open)return null;return <div className="adm-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><section className="adm-modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="adm-icon-btn" onClick={onClose} aria-label="Close"><X size={18}/></button></header><div className="adm-modal-body">{children}</div>{footer&&<footer>{footer}</footer>}</section></div>}
export function RowLink({href,label="View"}:{href:string;label?:string}){return <a className="adm-row-link" href={href}>{label}<ChevronRight size={14}/></a>}
