"use client";
import { useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { api,assetUrl } from "@/lib/api";
import { AdminPageHeader,Panel,StatusBadge } from "@/components/admin/AdminUI";
import { Upload,Star,Trash2,ImagePlus,Save,ArrowLeft } from "lucide-react";

const slugify=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:4000/api";
 export default function ProductEditor({id}:{id?:string}){
  const router=useRouter(); const [categories,setCategories]=useState<any[]>([]);const[product,setProduct]=useState<any>(null);const[saving,setSaving]=useState(false);const[notice,setNotice]=useState("");const[uploading,setUploading]=useState(false);const[imageUrl,setImageUrl]=useState("");const[imageAlt,setImageAlt]=useState("");
  const [form,setForm]=useState<any>({name:"",slug:"",sku:"",shortDescription:"",description:"",categoryId:"",subcategory:"",sport:"",gender:"Unisex",fabric:"",fit:"",productType:"Standard",imageUrl:"/images/official/11_black_green_custom_kit.jpg",altText:"",featured:false,isCustomizable:false,teamOrderEligible:false,showPrice:false,price:"",stockQuantity:100,lowStockThreshold:10,status:"DRAFT",seoTitle:"",seoDescription:""});
  const update=(key:string,value:any)=>setForm((f:any)=>({...f,[key]:value}));
  const load=async()=>{const cats=await api<any>("/admin/categories");setCategories(cats.categories||[]);if(!id){if(cats.categories?.[0])update("categoryId",cats.categories[0].id);return;}const r=await api<any>("/admin/products");const p=r.products.find((x:any)=>x.id===id);if(p){setProduct(p);setForm({...form,...p,categoryId:p.categoryId||p.category?.id,sku:p.sku||"",sport:p.sport||"",fabric:p.fabric||"",fit:p.fit||"",altText:p.altText||"",seoTitle:p.seoTitle||"",seoDescription:p.seoDescription||"",price:p.pricePence!=null?(p.pricePence/100).toFixed(2):"",showPrice:Boolean(p.showPrice)})}};
  useEffect(()=>{load()},[id]);
  const selectedCategory=useMemo(()=>categories.find(c=>c.id===form.categoryId),[categories,form.categoryId]);
  const subs=Array.isArray(selectedCategory?.subcategories)?selectedCategory.subcategories:[];
  const save=async()=>{setSaving(true);setNotice("");try{const parsedPrice=form.price!==""&&!isNaN(Number(form.price))&&Number(form.price)>=0?Math.round(Number(form.price)*100):null;const payload={...form,slug:form.slug||slugify(form.name),sku:form.sku||null,pricePence:parsedPrice,showPrice:parsedPrice!=null?Boolean(form.showPrice):false,stockQuantity:Number(form.stockQuantity||0),lowStockThreshold:Number(form.lowStockThreshold||0)};let saved:any;if(id){saved=await api<any>(`/admin/products/${id}`,{method:"PATCH",body:JSON.stringify(payload)});}else{saved=await api<any>("/admin/products",{method:"POST",body:JSON.stringify(payload)});}setNotice("Product saved successfully.");if(!id)router.replace(`/admin/products/${saved.product.id}/edit`);else{setProduct(saved.product)}}catch(e:any){setNotice(e.message)}finally{setSaving(false)}};
  const upload=async(file:File)=>{setUploading(true);setNotice("");try{const fd=new FormData();fd.append("file",file);const res=await fetch(`${API}/uploads`,{method:"POST",credentials:"include",body:fd});const body=await res.json();if(!res.ok)throw new Error(body?.error?.message||"Upload failed");if(!id){update("imageUrl",body.url);update("altText",form.altText||form.name);setNotice("Image uploaded. Save the product to create its gallery.");return;}await api(`/admin/products/${id}/images`,{method:"POST",body:JSON.stringify({url:body.url,alt:form.name||"XLIME GEAR product image",setCover:!product?.images?.length})});await load();setNotice("Image uploaded to gallery.")}catch(e:any){setNotice(e.message)}finally{setUploading(false)}};
  const addUrl=async()=>{if(!imageUrl.trim())return;if(!id){update("imageUrl",imageUrl.trim());update("altText",imageAlt||form.name);setImageUrl("");return;}await api(`/admin/products/${id}/images`,{method:"POST",body:JSON.stringify({url:imageUrl.trim(),alt:imageAlt||`${form.name} product image`})});setImageUrl("");setImageAlt("");await load()};
  const cover=async(imageId:string)=>{await api(`/admin/products/${id}/images/${imageId}/cover`,{method:"PATCH"});await load()};
  const removeImage=async(imageId:string)=>{if(!confirm("Remove this image from the product gallery?"))return;await api(`/admin/products/${id}/images/${imageId}`,{method:"DELETE"});await load()};
  return <>
   <AdminPageHeader eyebrow="CATALOG / PRODUCT" title={id?"Edit Product":"Add Product"} description="Create performance-ready catalog data, image metadata and search-friendly content." actions={<><button className="adm-btn" onClick={()=>router.back()}><ArrowLeft size={14}/>Back</button><button className="adm-btn primary" onClick={save} disabled={saving}><Save size={14}/>{saving?"Saving…":"Save Changes"}</button></>}/>
   {notice&&<div style={{marginBottom:12,padding:"10px 12px",border:"1px solid var(--adm-border)",borderRadius:8,color:notice.toLowerCase().includes("success")?"var(--adm-lime)":"var(--adm-warning)"}}>{notice}</div>}
   <div className="adm-detail-grid">
    <div className="adm-grid">
     <Panel title="Basic Information"><div className="adm-detail-block"><div className="adm-form-grid"><div className="adm-field"><label>Product name *</label><input className="adm-input" value={form.name} onChange={e=>{update("name",e.target.value);if(!id)update("slug",slugify(e.target.value));if(!form.altText)update("altText",`${e.target.value} by XLIME GEAR`)}}/></div><div className="adm-field"><label>SKU</label><input className="adm-input" value={form.sku||""} onChange={e=>update("sku",e.target.value)} placeholder="XG-0001"/></div><div className="adm-field"><label>Slug *</label><input className="adm-input" value={form.slug} onChange={e=>update("slug",slugify(e.target.value))}/></div><div className="adm-field"><label>Status</label><select className="adm-select" value={form.status} onChange={e=>update("status",e.target.value)}><option>ACTIVE</option><option>DRAFT</option><option>ARCHIVED</option></select></div><div className="adm-field wide"><label>Short description *</label><input className="adm-input" value={form.shortDescription} onChange={e=>update("shortDescription",e.target.value)} maxLength={500}/></div><div className="adm-field wide"><label>Full description *</label><textarea className="adm-textarea" value={form.description} onChange={e=>update("description",e.target.value)}/></div></div></div></Panel>
     <Panel title="Classification"><div className="adm-detail-block"><div className="adm-form-grid"><div className="adm-field"><label>Category</label><select className="adm-select" value={form.categoryId} onChange={e=>update("categoryId",e.target.value)}>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div><div className="adm-field"><label>Subcategory</label>{subs.length?<select className="adm-select" value={form.subcategory} onChange={e=>update("subcategory",e.target.value)}><option value="">Select</option>{subs.map((s:string)=><option key={s}>{s}</option>)}</select>:<input className="adm-input" value={form.subcategory} onChange={e=>update("subcategory",e.target.value)}/>}</div><div className="adm-field"><label>Sport / use</label><input className="adm-input" value={form.sport||""} onChange={e=>update("sport",e.target.value)} placeholder="Football, Fitness, Lifestyle"/></div><div className="adm-field"><label>Gender</label><select className="adm-select" value={form.gender} onChange={e=>update("gender",e.target.value)}><option>Unisex</option><option>Men</option><option>Women</option><option>Junior</option></select></div><div className="adm-field"><label>Fabric</label><input className="adm-input" value={form.fabric||""} onChange={e=>update("fabric",e.target.value)} placeholder="Performance polyester"/></div><div className="adm-field"><label>Fit</label><input className="adm-input" value={form.fit||""} onChange={e=>update("fit",e.target.value)} placeholder="Athletic fit"/></div></div><div className="adm-toolbar" style={{marginTop:14}}><label><input type="checkbox" checked={form.featured} onChange={e=>update("featured",e.target.checked)}/> Featured</label><label><input type="checkbox" checked={form.isCustomizable} onChange={e=>update("isCustomizable",e.target.checked)}/> Customisable</label><label><input type="checkbox" checked={form.teamOrderEligible} onChange={e=>update("teamOrderEligible",e.target.checked)}/> Team order eligible</label></div></div></Panel>
     <Panel title="Pricing & Inventory" subtitle="Enter price in GBP. Public visibility requires both product-level enablement and global showPublicPrices in store settings."><div className="adm-detail-block"><div className="adm-form-grid"><div className="adm-field"><label>Price (£ GBP)</label><input type="number" step="0.01" min="0" className="adm-input" value={form.price} onChange={e=>{const v=e.target.value;update("price",v);if(v&&!form.showPrice)update("showPrice",true)}} placeholder="45.00"/></div><div className="adm-field"><label>Stock quantity</label><input type="number" className="adm-input" value={form.stockQuantity??0} onChange={e=>update("stockQuantity",Number(e.target.value))}/></div><div className="adm-field"><label>Low stock threshold</label><input type="number" className="adm-input" value={form.lowStockThreshold??10} onChange={e=>update("lowStockThreshold",Number(e.target.value))}/></div></div><div className="adm-toolbar" style={{marginTop:14}}><label><input type="checkbox" checked={Boolean(form.showPrice)} onChange={e=>update("showPrice",e.target.checked)}/> Show price when public pricing is enabled</label></div></div></Panel>
     <Panel title="Product Images" subtitle="Use descriptive alt text. The cover image is used on listings and social previews."><div className="adm-detail-block"><div className="adm-form-grid"><div className="adm-field"><label>Add image URL</label><input className="adm-input" value={imageUrl} onChange={e=>setImageUrl(e.target.value)} placeholder="https://… or /images/…"/></div><div className="adm-field"><label>Image alt text</label><input className="adm-input" value={imageAlt} onChange={e=>setImageAlt(e.target.value)} placeholder={`${form.name||"Product"} front view`}/></div></div><div className="adm-toolbar" style={{marginTop:10}}><button className="adm-btn" onClick={addUrl}><ImagePlus size={14}/>Add URL</button><label className="adm-btn"><Upload size={14}/>{uploading?"Uploading…":"Upload File"}<input type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></div><div className="adm-media-grid" style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(140px,1fr))",gap:9,marginTop:14}}>{(product?.images||[]).map((img:any)=><div key={img.id} style={{border:"1px solid var(--adm-border)",borderRadius:8,overflow:"hidden",background:"var(--adm-surface2)"}}><img src={assetUrl(img.url)} alt={img.alt} style={{width:"100%",aspectRatio:"1",objectFit:"cover",background:"#fff"}}/><div style={{padding:8}}><small style={{display:"block",height:30,overflow:"hidden",color:"var(--adm-muted)"}}>{img.alt}</small><div style={{display:"flex",gap:5,marginTop:6}}><button className="adm-icon-btn" title="Set cover" onClick={()=>cover(img.id)}><Star size={13}/></button><button className="adm-icon-btn" title="Delete" onClick={()=>removeImage(img.id)}><Trash2 size={13}/></button></div></div></div>)}</div></div></Panel>
     <Panel title="Search & Social Metadata"><div className="adm-detail-block"><div className="adm-form-grid"><div className="adm-field wide"><label>SEO title</label><input className="adm-input" value={form.seoTitle||""} onChange={e=>update("seoTitle",e.target.value)} placeholder={`${form.name||"Product"} | XLIME GEAR`}/></div><div className="adm-field wide"><label>Meta description</label><textarea className="adm-textarea" value={form.seoDescription||""} onChange={e=>update("seoDescription",e.target.value)} maxLength={320}/></div><div className="adm-field wide"><label>Primary image alt text</label><input className="adm-input" value={form.altText||""} onChange={e=>update("altText",e.target.value)}/></div></div></div></Panel>
    </div>
    <aside className="adm-grid" style={{alignContent:"start"}}><Panel title="Live Status"><div className="adm-detail-block"><StatusBadge value={form.status}/><dl className="adm-detail-list" style={{marginTop:16}}><div><dt>Category</dt><dd>{selectedCategory?.name||"—"}</dd></div><div><dt>Sport</dt><dd>{form.sport||"—"}</dd></div><div><dt>Price</dt><dd>{form.price?`£${Number(form.price).toFixed(2)}`:"Not set"}</dd></div><div><dt>Product pricing</dt><dd>{form.showPrice?"Active":"Hidden"}</dd></div><div><dt>Customisable</dt><dd>{form.isCustomizable?"Yes":"No"}</dd></div></dl></div></Panel><Panel title="Storefront Preview"><div style={{padding:12}}><div style={{aspectRatio:"1",background:"#fff",borderRadius:8,overflow:"hidden"}}><img src={assetUrl(form.imageUrl||"/images/official/11_black_green_custom_kit.jpg")} alt={form.altText||form.name||"XLIME GEAR product"} style={{width:"100%",height:"100%",objectFit:"cover"}}/></div><h3 style={{font:"800 20px var(--font-barlow)",textTransform:"uppercase",margin:"12px 0 4px"}}>{form.name||"Product name"}</h3><p style={{fontSize:10,color:"var(--adm-muted)",lineHeight:1.5}}>{form.shortDescription||"Short description appears here."}</p></div></Panel></aside>
   </div>
  </>
 }
